---
- hosts: servers
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Initialize nginx
      service:
        name: nginx
        state: started

